server:
  port: 9000
  session:
    timeout: 500
  context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 2147483647

eureka:
  client:
    serviceUrl:
      defaultZone:  http://10.168.0.17:1111/eureka/
  instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://10.168.0.17:3306/auth?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: K@yUGP^K0kBRc0#X
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
  redis:
        database: 2
        host: 172.17.0.12
        port: 6379
        timeout: 3000
        pool.max-idle: 500
        pool.min-idle: 50
        pool.max-active: 2000
        pool.max-wait: 1000

ribbon:
    eager-load:
       enabled: true
    ReadTimeout: 60000
    ConnectTimeout: 60000

hystrix:
   command:
     default:
       execution:
         isolation:
           thread:
             timeoutInMilliseconds: 60000
