server:
  port: 8000
  connection-timeout: 2000
spring:
  profiles:
    active: dev
  application:
    name: blog-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none