server:
  port: 80

spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
