eureka:
  client:
    serviceUrl:
      defaultZone: http://10.168.0.17:1111/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10